server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.200.130:3306/user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
  application:
    name: userServer

  # nacos 地址
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ # 集群名称
      # 同一环境下得资源才能相互访问， 都需要标记
#        namespace: 492a7d5d-237b-46a1-a99a-fa8e98e4b0f9 # 命名空间，填ID

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

